# numpy基础

In [2]:
import numpy as np

## 在深度学习中，我们经常需要对一些参数进行初始化，此时需要用到np.random模块

In [11]:
np.random.seed(24) # 设置随机种子
a1 = np.random.random([3,3]) # 生成0-1之间的随机数
a2 = np.random.uniform(low=1, high=2, size=[3,3]) # 生成均匀分布随机数
a3 = np.random.randn(3,3) # 生成标准正态分布随机数
a4 = np.random.rand(3,3) # 生成0-1均匀分布随机数
a5 = np.random.normal(loc=2, scale=1, size=[3,3]) #生成正态分布随机数
np.random.shuffle(a5) # 将a5原地随机打乱顺序

print(a1,a2,a3,a4,a5, sep="\n")

[[0.9600173  0.69951205 0.99986729]
 [0.2200673  0.36105635 0.73984099]
 [0.99645573 0.31634698 0.13654458]]
[[1.38398001 1.32051928 1.36641475]
 [1.70965156 1.90014243 1.53411544]
 [1.24729376 1.67180656 1.56172911]]
[[ 0.9615384   0.1040112  -0.48116532]
 [ 0.85022853  1.45342467  1.05773744]
 [ 0.16556161  0.51501838 -1.33693569]]
[[0.48603187 0.8072193  0.84422015]
 [0.53468087 0.75779805 0.49967689]
 [0.8503279  0.61969678 0.86161418]]
[[1.00118488 2.34801251 1.78122233]
 [2.56286114 1.48745919 0.59363975]
 [1.0077771  2.67669018 2.08720091]]
[[1.00118488 2.34801251 1.78122233]
 [2.56286114 1.48745919 0.59363975]
 [1.0077771  2.67669018 2.08720091]]


## 创建特定形状的多维数组

In [15]:
b1 = np.zeros([3,4]) # 创建3x4全0数组
b2 = np.ones([3,4]) # 创建3x4全1数组
b3 = np.empty([3,4]) # 创建3x4空数组，空数组中的值是未初始化的垃圾值
b4 = np.zeros_like(b1) # 创建形状与b1相同的全0数组
b5 = np.ones_like(b2)
b6 = np.empty_like(b3)
b7 = np.eye(5) # 创建5x5单位矩阵
b8 = np.full([3,4], 666) # 创建3x4的值全为666的矩阵
b9 = np.diag([1,2,3]) # 对角元素为1,2,3的对角阵
b9

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## 数组变形
在机器学习以及深度学习中通常需要将处理好的数据以模型能够接受的格式输入给模型

In [55]:
a = np.random.random([2,3])
a1 = a.reshape(3,2) # 将数组a的形状改变，不修改数组本身
a.resize(3,2) # 修改数组本身
print(a)
a2 = a.ravel() # 将多维数组变成1维数组，数组元素按行序排列
# a2 = a.ravel("F") # 按列序排列
a3 = a.flatten() # 将多维数组变成1维数组，数组元素按行序排列, 该操作经常出现在卷积网络与全连接层之间
a3 = a3.reshape(-1, 1)
print(a3)
a4 = a3.squeeze() # 只对维数为1的维度降维
a5 = a.reshape([2,3,1])
print(a5)
a6 = a5.transpose([1,0,2]) # 对高维矩阵进行轴变换
print(a6)


[[1.49610438e-01 9.78271450e-01]
 [4.09506116e-02 2.18705772e-04]
 [8.68306679e-01 1.06728342e-01]]
[[1.49610438e-01]
 [9.78271450e-01]
 [4.09506116e-02]
 [2.18705772e-04]
 [8.68306679e-01]
 [1.06728342e-01]]
[[[1.49610438e-01]
  [9.78271450e-01]
  [4.09506116e-02]]

 [[2.18705772e-04]
  [8.68306679e-01]
  [1.06728342e-01]]]
[[[1.49610438e-01]
  [2.18705772e-04]]

 [[9.78271450e-01]
  [8.68306679e-01]]

 [[4.09506116e-02]
  [1.06728342e-01]]]


In [40]:
target = torch.empty([5,3], dtype=torch.long)

In [45]:
a = torch.FloatTensor([[1,2,3]])
torch.max(a, 1)

torch.return_types.max(
values=tensor([3.]),
indices=tensor([2]))

# pytorch安装

## 安装gpu版本的pytorch
1. 安装NVIDIA驱动https://www.nvidia.cn/Download/index.aspx?lang=cn
![title](./img/nvidia.png)
2. 安装完成后，在命令行输入nvidia-smi显示显卡基本信息 // linux系统下
3. 安装CUDA，安装时需要与英伟达GPU驱动版本一致，保证CUDA可以找到显卡
cuda(compute unified device architecture)是英伟达公司推出的一种基于新的并行编程模型的指令集架构的通用计算框架，
它能够利用GPU的并行计算引擎。
4. 安装cuDNN // 需要注册英伟达账号
NVIDIA cuDNN是用于深度神经网络的GPU加速库
5. 将cudnn解压之后的bin、include和lib文件夹拷贝到cuda目录下并进行替换
6. 将cuda的bin目录添加到环境变量
7. 在命令行使用nvcc -V查看是否安装成功
8. 在cuda和cudnn安装成功之后，取pytorch官网安装相应的pytorch